-- JAIN COMMUNITY KARNAL
-- Run this whole file in Supabase SQL Editor.
-- Then create organizer accounts in Supabase Authentication → Users.
create extension if not exists pgcrypto;

create table if not exists public.families(
 id uuid primary key default gen_random_uuid(),
 name text not null unique,
 created_at timestamptz not null default now()
);

create table if not exists public.members(
 id uuid primary key default gen_random_uuid(),
 name text not null,
 family_id uuid references public.families(id) on delete set null,
 phone text,
 email text,
 created_at timestamptz not null default now()
);

create table if not exists public.events(
 id bigint generated by default as identity primary key,
 title text not null,
 description text,
 event_date date not null,
 event_time time not null,
 location text,
 category text default 'Community',
 capacity integer not null default 100 check(capacity>0),
 registration_open boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.event_registrations(
 id bigint generated by default as identity primary key,
 event_id bigint not null references public.events(id) on delete cascade,
 name text not null,
 family text,
 phone text not null,
 participants integer not null default 1 check(participants between 1 and 10),
 created_at timestamptz not null default now()
);

create table if not exists public.paath_slots(
 id bigint generated by default as identity primary key,
 slot_date date not null,
 start_hour integer not null check(start_hour between 0 and 23),
 capacity integer not null default 4 check(capacity between 1 and 4),
 unique(slot_date,start_hour)
);

create table if not exists public.paath_bookings(
 id bigint generated by default as identity primary key,
 slot_id bigint not null references public.paath_slots(id) on delete cascade,
 name text not null,
 family text,
 phone text not null,
 created_at timestamptz not null default now()
);

-- Generate a default 10-day x 24-hour grid for 10–19 Sep 2026.
insert into public.paath_slots(slot_date,start_hour)
select d::date,h
from generate_series(date '2026-09-10',date '2026-09-19',interval '1 day') d
cross join generate_series(0,23) h
on conflict(slot_date,start_hour) do nothing;

create or replace view public.event_public as
select e.*, coalesce(sum(r.participants),0)::integer as registered
from public.events e
left join public.event_registrations r on r.event_id=e.id
group by e.id;

create or replace view public.paath_slot_public as
select s.*, count(b.id)::integer as booked
from public.paath_slots s
left join public.paath_bookings b on b.slot_id=s.id
group by s.id;

create or replace view public.member_public as
select m.id,m.name, f.name as family
from public.members m left join public.families f on f.id=m.family_id;

-- Atomic event registration: prevents exceeding capacity.
create or replace function public.register_for_event(
 p_event_id bigint,p_name text,p_family text,p_phone text,p_participants integer
) returns void language plpgsql security definer set search_path=public as $$
declare cap integer; used integer;
begin
 if p_participants<1 or p_participants>10 then raise exception 'Invalid participant count'; end if;
 select capacity into cap from events where id=p_event_id and registration_open=true for update;
 if cap is null then raise exception 'Event is not available for registration'; end if;
 select coalesce(sum(participants),0) into used from event_registrations where event_id=p_event_id;
 if used+p_participants>cap then raise exception 'Only % places remain', cap-used; end if;
 insert into event_registrations(event_id,name,family,phone,participants)
 values(p_event_id,trim(p_name),nullif(trim(p_family),''),trim(p_phone),p_participants);
end $$;

-- Atomic Paath booking: locks slot and checks capacity.
create or replace function public.book_paath_slot(
 p_slot_id bigint,p_name text,p_family text,p_phone text
) returns void language plpgsql security definer set search_path=public as $$
declare cap integer; used integer;
begin
 select capacity into cap from paath_slots where id=p_slot_id for update;
 if cap is null then raise exception 'Slot not found'; end if;
 select count(*) into used from paath_bookings where slot_id=p_slot_id;
 if used>=cap then raise exception 'This Paath slot is full'; end if;
 insert into paath_bookings(slot_id,name,family,phone)
 values(p_slot_id,trim(p_name),nullif(trim(p_family),''),trim(p_phone));
end $$;

alter table public.families enable row level security;
alter table public.members enable row level security;
alter table public.events enable row level security;
alter table public.event_registrations enable row level security;
alter table public.paath_slots enable row level security;
alter table public.paath_bookings enable row level security;

-- Public read access is deliberately limited to safe views.
grant select on public.event_public to anon,authenticated;
grant select on public.paath_slot_public to anon,authenticated;
grant select on public.member_public to anon,authenticated;

-- Public registration/booking uses security-definer functions above.
grant execute on function public.register_for_event(bigint,text,text,text,integer) to anon,authenticated;
grant execute on function public.book_paath_slot(bigint,text,text,text) to anon,authenticated;

-- Organizer access: any authenticated user is treated as organizer in this starter.
-- For production, replace this with a user_roles table + RLS policy for specific organizers.
create policy "authenticated manage events" on public.events for all to authenticated using(true) with check(true);
create policy "authenticated view registrations" on public.event_registrations for select to authenticated using(true);
create policy "authenticated manage registrations" on public.event_registrations for all to authenticated using(true) with check(true);
create policy "authenticated manage members" on public.members for all to authenticated using(true) with check(true);
create policy "authenticated manage families" on public.families for all to authenticated using(true) with check(true);
create policy "authenticated manage paath slots" on public.paath_slots for all to authenticated using(true) with check(true);
create policy "authenticated view paath bookings" on public.paath_bookings for select to authenticated using(true);
create policy "authenticated manage paath bookings" on public.paath_bookings for all to authenticated using(true) with check(true);

-- Seed a few community members.
insert into public.families(name) values
('Jain Family'),('Sec. 4'),('Anurag Jain Family'),('Ajay Jain Family')
on conflict(name) do nothing;

insert into public.members(name,family_id)
select x.name,f.id from (values
('Umang Jain','Jain Family'),('Anjali Jain','Jain Family'),('Lakshveer Jain','Jain Family'),
('Atul Jain','Jain Family'),('Shilpa Jain','Jain Family'),('Samyak Jain','Jain Family'),
('Saurabh Jain','Sec. 4'),('Aachran Jain','Jain Family'),('Ankit Jain','Jain Family'),
('Piyush Jain','Jain Family'),('Khushboo Jain','Jain Family'),('Arham Jain','Jain Family'),
('Soham Jain','Jain Family'),('Sandip Jain','Jain Family'),('Sachin Jain','Jain Family'),
('Ritu Jain','Jain Family'),('Shuchi Jain','Anurag Jain Family'),('Ajay Jain','Jain Family'),
('Prachi Jain','Ajay Jain Family'),('Aagam Jain','Ajay Jain Family')
) x(name,family) join public.families f on f.name=x.family
where not exists(select 1 from public.members m where m.name=x.name and m.family_id=f.id);

insert into public.events(title,event_date,event_time,category,capacity,description,registration_open)
values
('Samvatsari Community Programme','2026-09-13','18:00','Festival',250,'Community gathering and programme.',true),
('Daslakshan Parv – Community Gathering','2026-09-20','19:00','Parv',200,'Community programme during Daslakshan Parv.',true)
on conflict do nothing;
